name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  windows:
    strategy:
      matrix:
        os-version: ['x64', 'arm64']

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm fetchcore
          pnpm run build:win-${{ matrix.os-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: rename
        run: |
          cd .\dist
          mv *.exe FinalDream-windows-${{ matrix.os-version }}.exe

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd .\dist\win-unpacked
          7z a -r FinalDream-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd .\dist\win-arm64-unpacked
          7z a -r FinalDream-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-unpacked/*.7z

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-arm64-unpacked/*.7z

      - name: upload-setup
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-windows-${{ matrix.os-version }}-exe
          path: dist/*.exe

  macos:
    strategy:
      matrix:
        os-version: ['x64', 'arm64']

    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm fetchcore
          pnpm run build:mac-${{ matrix.os-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: rename
        run: |
          cd ./dist
          mv *.dmg FinalDream-macos-${{ matrix.os-version }}-dmg.dmg

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd ./dist/mac
          7z a -r FinalDream-macos-${{ matrix.os-version }}-unpacked.7z *

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd ./dist/mac-arm64
          7z a -r FinalDream-macos-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-dmg
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-macos-${{ matrix.os-version }}-dmg
          path: dist/*.dmg

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-macos-${{ matrix.os-version }}-unpacked
          path: dist/mac/*.7z

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-macos-${{ matrix.os-version }}-unpacked
          path: dist/mac-arm64/*.7z

  linux:
    strategy:
      matrix:
        os-version: ['x64']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build
        run: |
          pnpm install
          pnpm run build:linux-${{ matrix.os-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked
        run: |
          cd ./dist/linux-unpacked
          7z a -r FinalDream-linux-pip-${{ matrix.os-version }}-unpacked.7z *

      - name: rename
        run: |
          cd ./dist
          mv *.snap FinalDream-linux-pip-${{ matrix.os-version }}-snap.snap
          mv *.AppImage FinalDream-linux-pip-${{ matrix.os-version }}-AppImage.AppImage
          mv *.deb FinalDream-linux-pip-${{ matrix.os-version }}-deb.deb

      - name: upload-snap
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-linux-pip-${{ matrix.os-version }}-snap
          path: dist/*.snap

      - name: upload-AppImage
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-linux-pip-${{ matrix.os-version }}-AppImage
          path: dist/*.AppImage

      - name: upload-deb
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-linux-pip-${{ matrix.os-version }}-deb
          path: dist/*.deb

      - name: upload-unpacked
        uses: actions/upload-artifact@v4
        with:
          name: FinalDream-linux-pip-${{ matrix.os-version }}-unpacked
          path: dist/linux-unpacked/*.7z

  github:
    needs: [windows, macos, linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: asset

      - name: Flatten asset directory
        run: |
          tree asset
          mkdir dist
          find asset -type f -print0 | xargs -0 -I{} cp "{}" dist/
          cd dist && ls -l

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
